import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { Order, OrderItem, Product, ReportDefinition, Settings } from '@/db/models'
import { productTotalCost } from '@/db/models'
import { formatMoney } from '@/utils/money'
import { formatRange } from '@/utils/dates'

const TEAL: [number, number, number] = [15, 118, 110]
const INK: [number, number, number] = [30, 41, 59]
const MUTED: [number, number, number] = [100, 116, 139]
const WHITE: [number, number, number] = [255, 255, 255]
const ROW_ALT: [number, number, number] = [241, 245, 249]

export interface PdfContext {
  settings?: Settings
  logoDataUrl?: string
}

type LastAutoTable = { lastAutoTable?: { finalY: number } }

function finalY(doc: jsPDF, fallback: number): number {
  return (doc as unknown as LastAutoTable).lastAutoTable?.finalY ?? fallback
}

/** Shop letterhead + report title. Returns the Y cursor below the block. */
function drawHeader(doc: jsPDF, ctx: PdfContext, title: string, subtitle?: string): number {
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 14
  const hasLogo = Boolean(ctx.logoDataUrl)

  if (hasLogo && ctx.logoDataUrl) {
    try {
      doc.addImage(ctx.logoDataUrl, 'PNG', 14, y - 4, 16, 16)
    } catch {
      /* corrupted logo — fall back to text-only */
    }
  }

  const textX = hasLogo ? 34 : 14
  doc.setTextColor(...INK)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text(ctx.settings?.shopName?.trim() || 'Etsy Shop', textX, y + 4)

  if (ctx.settings?.address) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...MUTED)
    const lines = doc.splitTextToSize(ctx.settings.address, pageWidth - textX - 14) as string[]
    doc.text(lines, textX, y + 9)
    y += 9 + lines.length * 3.5
  } else {
    y += 8
  }

  y += 6
  doc.setDrawColor(...TEAL)
  doc.setLineWidth(0.6)
  doc.line(14, y, pageWidth - 14, y)
  y += 8
  doc.setTextColor(...TEAL)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text(title, 14, y)
  y += 6
  if (subtitle) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(...MUTED)
    doc.text(subtitle, 14, y)
    y += 4
  }
  return y + 6
}

function addFooters(doc: jsPDF): void {
  const pages = doc.internal.getNumberOfPages()
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...MUTED)
    doc.text(`Page ${i} of ${pages}`, pageWidth - 14, pageHeight - 8, { align: 'right' })
    doc.text('Generated by Munim', 14, pageHeight - 8)
  }
}

/** Generic report → professional multi-page PDF (title, period, summary, table, page numbers). */
export function reportToPdf(def: ReportDefinition, ctx: PdfContext = {}): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const subtitle =
    def.from && def.to
      ? `Period: ${formatRange({ from: def.from, to: def.to })}`
      : `Generated ${new Date().toLocaleString()}`
  let y = drawHeader(doc, ctx, def.title, subtitle)

  if (def.summary.length) {
    autoTable(doc, {
      startY: y,
      head: [def.summary.map((s) => s.label)],
      body: [def.summary.map((s) => String(s.value))],
      theme: 'plain',
      styles: { fontSize: 9, textColor: INK, cellPadding: 2 },
      headStyles: { fontStyle: 'normal', textColor: MUTED, fontSize: 8 },
      margin: { left: 14, right: 14 },
    })
    y = finalY(doc, y) + 6
  }

  autoTable(doc, {
    startY: y,
    head: [def.columns.map((c) => c.label)],
    body: def.rows.map((r) => def.columns.map((c) => String(r[c.key] ?? ''))),
    styles: { fontSize: 9, textColor: INK, cellPadding: 2.5, overflow: 'linebreak' },
    headStyles: { fillColor: TEAL, textColor: WHITE, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: ROW_ALT },
    margin: { left: 14, right: 14 },
    columnStyles: Object.fromEntries(
      def.columns.flatMap((c, i) =>
        c.align === 'right' ? ([[i, { halign: 'right' as const }]] as const) : [],
      ),
    ),
  })

  addFooters(doc)
  return doc
}

function costLookup(products: Product[]): {
  bySku: Map<string, Product>
  byName: Map<string, Product>
} {
  return {
    bySku: new Map(products.filter((p) => p.sku).map((p) => [p.sku!, p])),
    byName: new Map(products.map((p) => [p.name.trim().toLowerCase(), p])),
  }
}

/** Draw one order's summary onto the doc's current page. Returns final Y. */
function drawOrderPage(
  doc: jsPDF,
  ctx: PdfContext,
  order: Order,
  items: OrderItem[],
  products: Product[],
): number {
  const currency = order.currency || ctx.settings?.currency || 'USD'
  const m = (n: number) => formatMoney(n, currency)

  const subtitle = `Order ${order.orderNumber || order.id} · ${new Date(order.date).toLocaleDateString()}`
  let y = drawHeader(doc, ctx, 'Order Summary', subtitle)

  doc.setTextColor(...INK)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.text('Buyer', 14, y)
  doc.text('Ship to', 110, y)
  y += 5
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  const left = [order.buyerName || '—', order.buyerEmail, order.buyerCountry].filter(Boolean) as string[]
  const right = [
    order.street,
    [order.shipCity, order.shipState].filter(Boolean).join(', '),
    order.shipZip,
    order.shipCountry,
  ].filter(Boolean) as string[]
  doc.text(left, 14, y, { maxWidth: 90 })
  doc.text(right.length ? right : ['—'], 110, y, { maxWidth: 90 })
  y += Math.max(left.length, right.length) * 4.5 + 4

  const { bySku, byName } = costLookup(products)
  autoTable(doc, {
    startY: y,
    head: [['Item', 'Qty', 'Unit', 'Line total']],
    body: items.map((it) => {
      const product =
        (it.sku ? bySku.get(it.sku) : undefined) ?? byName.get(it.name.trim().toLowerCase())
      const label = product
        ? `${it.name} (cost ${m(productTotalCost(product))})`
        : it.name
      return [label, String(it.quantity), m(it.unitPrice), m(it.lineTotal)]
    }),
    styles: { fontSize: 9, textColor: INK, cellPadding: 2.5 },
    headStyles: { fillColor: TEAL, textColor: WHITE },
    margin: { left: 14, right: 14 },
    columnStyles: { 1: { halign: 'right' }, 2: { halign: 'right' }, 3: { halign: 'right' } },
  })

  y = finalY(doc, y) + 8

  const totals: { label: string; value: string; strong?: boolean }[] = [
    { label: 'Items total', value: m(order.itemTotal) },
    { label: 'Shipping', value: m(order.shippingCollected) },
    { label: 'Tax', value: m(order.taxTotal) },
    { label: 'Discounts', value: order.discounts ? `−${m(order.discounts)}` : m(0) },
    { label: 'Order total', value: m(order.orderTotal), strong: true },
  ]
  if (order.netAmount != null) {
    totals.push({ label: 'Net payout', value: m(order.netAmount), strong: true })
  }

  doc.setFontSize(9)
  for (const t of totals) {
    doc.setFont('helvetica', t.strong ? 'bold' : 'normal')
    doc.setTextColor(...(t.strong ? TEAL : INK))
    doc.text(t.label, 130, y)
    doc.text(t.value, 196, y, { align: 'right' })
    y += 5
  }

  if (order.notes) {
    y += 4
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...INK)
    doc.text('Notes', 14, y)
    y += 4
    doc.setFont('helvetica', 'normal')
    doc.text(doc.splitTextToSize(order.notes, 180) as string[], 14, y)
  }
  return y
}

/** Single-order invoice / summary. */
export function orderToPdf(
  order: Order,
  items: OrderItem[],
  settings: Settings | undefined,
  logoDataUrl: string | undefined,
  products: Product[],
): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  drawOrderPage(doc, { settings, logoDataUrl }, order, items, products)
  addFooters(doc)
  return doc
}

/** Bulk PDF: one order per page. */
export function ordersToPdf(
  orders: Order[],
  itemsByOrder: Map<string, OrderItem[]>,
  settings: Settings | undefined,
  logoDataUrl: string | undefined,
  products: Product[],
): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const ctx = { settings, logoDataUrl }
  orders.forEach((order, i) => {
    if (i > 0) doc.addPage()
    drawOrderPage(doc, ctx, order, itemsByOrder.get(order.id) ?? [], products)
  })
  addFooters(doc)
  return doc
}

export function downloadPdf(doc: jsPDF, filename: string): void {
  doc.save(filename)
}
